# Site
name: "Vikram Kone"
title: "Vikram Kone"
description: "Hi there. Welcome to my world!"
logo: 'assets/images/vikram.jpeg'
favicon: 'assets/images/vikram.jpeg'
baseurl: ''
url: 'https://vikramkone.github.io'
google_analytics: 'UA-17137344-4'
disqus: 'vikramkone'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: vikramkone@gmail.com

# Authors
authors:
  Vikram:
    name: Vikram
    display_name: Vikram
    gravatar:
    email: vikramkone@gmail.com
    web: https://www.vikramkone.com
    twitter: https://twitter.com/vikramkone
    description: "Data Nerd. Father of Vaaryan and Husband of Upasana. Love travel, food, movies and books."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rogue
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
